import { Issue, Notification } from './types';

export const mockIssues: Issue[] = [
  // 20 issues from STU001 (Ahmed Hassan) for "My Issues" testing
  {
    id: '1',
    title: 'Wifi not working in cafeteria',
    description: 'The wifi network is not connecting properly in the main cafeteria. This affects students trying to study.',
    category: 'Technology',
    status: 'Pending',
    studentId: 'STU001',
    studentName: 'Ahmed Hassan',
    submittedDate: '2026-04-22',
    agreementCount: 5,
    agreedBy: ['STU002', 'STU003'],
  },
  {
    id: 'MY2',
    title: 'Air conditioning not working in library',
    description: 'The AC system in the main library is broken. It\'s extremely hot and uncomfortable to study there.',
    category: 'Infrastructure',
    status: 'In Progress',
    studentId: 'STU001',
    studentName: 'Ahmed Hassan',
    submittedDate: '2026-04-20',
    agreementCount: 12,
    agreedBy: [],
  },
  {
    id: 'MY3',
    title: 'Broken water fountain near gym',
    description: 'The water fountain near the gym entrance is leaking and not dispensing water properly.',
    category: 'Infrastructure',
    status: 'Pending',
    studentId: 'STU001',
    studentName: 'Ahmed Hassan',
    submittedDate: '2026-04-18',
    agreementCount: 3,
    agreedBy: [],
  },
  {
    id: 'MY4',
    title: 'Cafeteria food quality issues',
    description: 'The food quality in the cafeteria has been declining. Many items taste stale or are cold when served.',
    category: 'Cafeteria',
    status: 'Resolved',
    studentId: 'STU001',
    studentName: 'Ahmed Hassan',
    submittedDate: '2026-04-15',
    agreementCount: 8,
    agreedBy: [],
  },
  {
    id: 'MY5',
    title: 'Broken chairs in classroom 301',
    description: 'Multiple chairs in classroom 301 are broken and unsafe to sit on. Students need proper seating.',
    category: 'Infrastructure',
    status: 'Pending',
    studentId: 'STU001',
    studentName: 'Ahmed Hassan',
    submittedDate: '2026-04-12',
    agreementCount: 7,
    agreedBy: [],
  },
  {
    id: 'MY6',
    title: 'Printer not working in computer lab',
    description: 'The main printer in the computer lab is offline and needs to be repaired or replaced.',
    category: 'Technology',
    status: 'Pending',
    studentId: 'STU001',
    studentName: 'Ahmed Hassan',
    submittedDate: '2026-04-10',
    agreementCount: 4,
    agreedBy: [],
  },
  {
    id: 'MY7',
    title: 'Bathroom doors broken in block E',
    description: 'The bathroom stall doors in Block E are broken. Privacy is a major concern.',
    category: 'Cleanliness',
    status: 'In Progress',
    studentId: 'STU001',
    studentName: 'Ahmed Hassan',
    submittedDate: '2026-04-08',
    agreementCount: 11,
    agreedBy: [],
  },
  {
    id: 'MY8',
    title: 'Unsafe stairs near dormitory',
    description: 'The stairs leading to the dormitory have loose steps and are a safety hazard.',
    category: 'Safety',
    status: 'Pending',
    studentId: 'STU001',
    studentName: 'Ahmed Hassan',
    submittedDate: '2026-04-05',
    agreementCount: 15,
    agreedBy: [],
  },
  {
    id: 'MY9',
    title: 'Lights flickering in hallway B',
    description: 'The lights in hallway B flicker constantly throughout the day and night.',
    category: 'Infrastructure',
    status: 'Pending',
    studentId: 'STU001',
    studentName: 'Ahmed Hassan',
    submittedDate: '2026-04-03',
    agreementCount: 2,
    agreedBy: [],
  },
  {
    id: 'MY10',
    title: 'Door lock broken in room 215',
    description: 'The lock on door 215 is broken. Students cannot properly secure their rooms.',
    category: 'Safety',
    status: 'Resolved',
    studentId: 'STU001',
    studentName: 'Ahmed Hassan',
    submittedDate: '2026-04-01',
    agreementCount: 6,
    agreedBy: [],
  },
  {
    id: 'MY11',
    title: 'Ventilation issues in dormitory',
    description: 'The ventilation system in the dormitory is not working. Rooms are stuffy and humid.',
    category: 'Infrastructure',
    status: 'Pending',
    studentId: 'STU001',
    studentName: 'Ahmed Hassan',
    submittedDate: '2026-03-30',
    agreementCount: 9,
    agreedBy: [],
  },
  {
    id: 'MY12',
    title: 'Internet connectivity issues in rooms',
    description: 'Many student rooms have poor internet connection. It\'s difficult to complete online assignments.',
    category: 'Technology',
    status: 'In Progress',
    studentId: 'STU001',
    studentName: 'Ahmed Hassan',
    submittedDate: '2026-03-28',
    agreementCount: 14,
    agreedBy: [],
  },
  {
    id: 'MY13',
    title: 'Pest issue in block C',
    description: 'There are insects and pests in Block C dormitory. Pest control is needed urgently.',
    category: 'Cleanliness',
    status: 'Pending',
    studentId: 'STU001',
    studentName: 'Ahmed Hassan',
    submittedDate: '2026-03-25',
    agreementCount: 10,
    agreedBy: [],
  },
  {
    id: 'MY14',
    title: 'Broken window in classroom 102',
    description: 'One of the windows in classroom 102 is cracked and broken. It needs to be replaced.',
    category: 'Infrastructure',
    status: 'Resolved',
    studentId: 'STU001',
    studentName: 'Ahmed Hassan',
    submittedDate: '2026-03-22',
    agreementCount: 3,
    agreedBy: [],
  },
  {
    id: 'MY15',
    title: 'Noisy neighborhood near campus',
    description: 'There is constant noise from the neighborhood. It disturbs students especially at night.',
    category: 'Safety',
    status: 'Pending',
    studentId: 'STU001',
    studentName: 'Ahmed Hassan',
    submittedDate: '2026-03-20',
    agreementCount: 5,
    agreedBy: [],
  },
  {
    id: 'MY16',
    title: 'Cleaning schedule not followed',
    description: 'The dormitory cleaning schedule is not being followed. Common areas are dirty.',
    category: 'Cleanliness',
    status: 'Pending',
    studentId: 'STU001',
    studentName: 'Ahmed Hassan',
    submittedDate: '2026-03-18',
    agreementCount: 7,
    agreedBy: [],
  },
  {
    id: 'MY17',
    title: 'Insufficient parking space',
    description: 'There is not enough parking space for students. Cars are parked illegally everywhere.',
    category: 'Others',
    status: 'In Progress',
    studentId: 'STU001',
    studentName: 'Ahmed Hassan',
    submittedDate: '2026-03-15',
    agreementCount: 18,
    agreedBy: [],
  },
  {
    id: 'MY18',
    title: 'Lab equipment needs maintenance',
    description: 'Various lab equipment in the science building needs regular maintenance and repair.',
    category: 'Technology',
    status: 'Pending',
    studentId: 'STU001',
    studentName: 'Ahmed Hassan',
    submittedDate: '2026-03-12',
    agreementCount: 4,
    agreedBy: [],
  },
  {
    id: 'MY19',
    title: 'Drinking water contamination concern',
    description: 'There are concerns about the water quality in some water fountains on campus.',
    category: 'Safety',
    status: 'Pending',
    studentId: 'STU001',
    studentName: 'Ahmed Hassan',
    submittedDate: '2026-03-10',
    agreementCount: 9,
    agreedBy: [],
  },
  {
    id: 'MY20',
    title: 'Inadequate lighting in parking area',
    description: 'The parking area is poorly lit at night. It\'s a safety concern for students.',
    category: 'Safety',
    status: 'Resolved',
    studentId: 'STU001',
    studentName: 'Ahmed Hassan',
    submittedDate: '2026-03-08',
    agreementCount: 12,
    agreedBy: [],
  },
  // Additional issues from other students for "All Issues" testing (30 more)
  {
    id: '2',
    title: 'Dormitory lighting too poor',
    description: 'The lights in my dorm room are too dim and flicker a lot at night. It\'s really hard to study or even move around comfortably. (Block B, Room 214)',
    category: 'Infrastructure',
    status: 'Pending',
    studentId: 'STU004',
    studentName: 'Fatima Ahmed',
    submittedDate: '2026-02-22',
    agreementCount: 2,
    agreedBy: [],
  },
  {
    id: '3',
    title: 'Damaged desk in room B2',
    description: 'One of the desks in room B2 is broken and needs to be repaired or replaced. It\'s unsafe to use.',
    category: 'Infrastructure',
    status: 'In Progress',
    studentId: 'STU005',
    studentName: 'Mohammed Ali',
    submittedDate: '2026-02-22',
    agreementCount: 1,
    agreedBy: [],
  },
  {
    id: '4',
    title: 'Broken projector in lab 2',
    description: 'The projector in lab 2 is not working. This affects practical sessions and presentations.',
    category: 'Technology',
    status: 'Resolved',
    studentId: 'STU006',
    studentName: 'Zainab Ibrahim',
    submittedDate: '2026-01-11',
    agreementCount: 8,
    agreedBy: [],
  },
  {
    id: '5',
    title: 'Cafeteria 2L water bottle shortage',
    description: 'The main cafeteria is running out of 2-liter water bottles. Students have difficulty getting water during peak hours.',
    category: 'Cafeteria',
    status: 'Pending',
    studentId: 'STU007',
    studentName: 'Omar Hassan',
    submittedDate: '2026-04-22',
    agreementCount: 3,
    agreedBy: [],
  },
  {
    id: '6',
    title: 'Ertib Runs Out Too Early in Cafeteria',
    description: 'Ertib finishes way before many of us arrive after Library. It\'s the main thing I look forward to and I keep missing it.',
    category: 'Cafeteria',
    status: 'In Progress',
    studentId: 'STU008',
    studentName: 'Sarah Hassan',
    submittedDate: '2026-01-31',
    agreementCount: 30,
    agreedBy: [],
  },
  {
    id: '7',
    title: 'Bathroom Cleanliness Issues',
    description: 'Bathrooms in Block D ground floor are not cleaned regularly. Hygiene conditions are poor. (Men\'s dorm block D)',
    category: 'Cleanliness',
    status: 'Resolved',
    studentId: 'STU009',
    studentName: 'Khaled Ahmed',
    submittedDate: '2025-12-22',
    agreementCount: 13,
    agreedBy: [],
  },
  {
    id: '8',
    title: 'Window Won\'t Close in Dorm Room',
    description: 'The window in my room (Block C, Room 203) won\'t shut properly. Cold air and noise come in all night.',
    category: 'Infrastructure',
    status: 'Pending',
    studentId: 'STU010',
    studentName: 'Layla Mohammed',
    submittedDate: '2026-02-12',
    agreementCount: 1,
    agreedBy: [],
  },
  {
    id: 'ALL9',
    title: 'Missing textbooks in library',
    description: 'Several important textbooks are missing from the library. Students cannot find them for their courses.',
    category: 'Technology',
    status: 'Pending',
    studentId: 'STU011',
    studentName: 'Hassan Karim',
    submittedDate: '2026-04-21',
    agreementCount: 6,
    agreedBy: [],
  },
  {
    id: 'ALL10',
    title: 'Slow internet speed on campus',
    description: 'Internet connectivity is very slow throughout the campus. It\'s affecting academic work.',
    category: 'Technology',
    status: 'In Progress',
    studentId: 'STU012',
    studentName: 'Noor Ibrahim',
    submittedDate: '2026-04-19',
    agreementCount: 22,
    agreedBy: [],
  },
  {
    id: 'ALL11',
    title: 'Leaking roof in dormitory block A',
    description: 'The roof in Block A is leaking. Water damage is visible in several rooms.',
    category: 'Infrastructure',
    status: 'Resolved',
    studentId: 'STU013',
    studentName: 'Amina Hassan',
    submittedDate: '2026-04-17',
    agreementCount: 11,
    agreedBy: [],
  },
  {
    id: 'ALL12',
    title: 'Crowded bus schedule',
    description: 'Campus buses are overcrowded and running behind schedule. Students are arriving late to classes.',
    category: 'Others',
    status: 'Pending',
    studentId: 'STU014',
    studentName: 'Tariq Mohamed',
    submittedDate: '2026-04-16',
    agreementCount: 19,
    agreedBy: [],
  },
  {
    id: 'ALL13',
    title: 'Cold water shortage in dorms',
    description: 'Cold water is not available in the dormitory during certain hours.',
    category: 'Infrastructure',
    status: 'In Progress',
    studentId: 'STU015',
    studentName: 'Hana Ahmed',
    submittedDate: '2026-04-14',
    agreementCount: 5,
    agreedBy: [],
  },
  {
    id: 'ALL14',
    title: 'Unsafe electrical wiring',
    description: 'Exposed electrical wiring in the science building is a safety hazard.',
    category: 'Safety',
    status: 'Pending',
    studentId: 'STU016',
    studentName: 'Yousef Ali',
    submittedDate: '2026-04-13',
    agreementCount: 8,
    agreedBy: [],
  },
  {
    id: 'ALL15',
    title: 'Dirty dormitory corridors',
    description: 'The corridors in the dormitory are not being cleaned properly. Trash accumulates.',
    category: 'Cleanliness',
    status: 'Pending',
    studentId: 'STU017',
    studentName: 'Sara Hassan',
    submittedDate: '2026-04-11',
    agreementCount: 7,
    agreedBy: [],
  },
  {
    id: 'ALL16',
    title: 'Broken shower fixtures',
    description: 'Many shower fixtures in the dormitory bathrooms are broken or leaking.',
    category: 'Infrastructure',
    status: 'Resolved',
    studentId: 'STU018',
    studentName: 'Rayan Mohammed',
    submittedDate: '2026-04-09',
    agreementCount: 9,
    agreedBy: [],
  },
  {
    id: 'ALL17',
    title: 'Inadequate study spaces',
    description: 'There are not enough quiet study areas for students. Libraries are always full.',
    category: 'Infrastructure',
    status: 'Pending',
    studentId: 'STU019',
    studentName: 'Dina Hassan',
    submittedDate: '2026-04-07',
    agreementCount: 16,
    agreedBy: [],
  },
  {
    id: 'ALL18',
    title: 'Air quality issues in classrooms',
    description: 'Some classrooms have poor air quality. Students report difficulty breathing during lectures.',
    category: 'Safety',
    status: 'In Progress',
    studentId: 'STU020',
    studentName: 'Malik Ahmed',
    submittedDate: '2026-04-06',
    agreementCount: 10,
    agreedBy: [],
  },
  {
    id: 'ALL19',
    title: 'Malfunctioning fire extinguishers',
    description: 'Fire extinguishers in several buildings appear to be outdated or non-functional.',
    category: 'Safety',
    status: 'Pending',
    studentId: 'STU021',
    studentName: 'Leila Hassan',
    submittedDate: '2026-04-04',
    agreementCount: 12,
    agreedBy: [],
  },
  {
    id: 'ALL20',
    title: 'Lack of wheelchair accessibility',
    description: 'Several buildings on campus lack proper wheelchair accessibility. This affects students with disabilities.',
    category: 'Safety',
    status: 'In Progress',
    studentId: 'STU022',
    studentName: 'Karim Hassan',
    submittedDate: '2026-04-02',
    agreementCount: 14,
    agreedBy: [],
  },
  {
    id: 'ALL21',
    title: 'Noisy construction near campus',
    description: 'Construction work near the campus is causing excessive noise affecting student studies.',
    category: 'Others',
    status: 'Pending',
    studentId: 'STU023',
    studentName: 'Fatima Hassan',
    submittedDate: '2026-03-31',
    agreementCount: 4,
    agreedBy: [],
  },
  {
    id: 'ALL22',
    title: 'Broken exercise equipment',
    description: 'Exercise equipment in the campus gym is broken and needs maintenance.',
    category: 'Infrastructure',
    status: 'Resolved',
    studentId: 'STU024',
    studentName: 'Ahmed Ibrahim',
    submittedDate: '2026-03-29',
    agreementCount: 6,
    agreedBy: [],
  },
  {
    id: 'ALL23',
    title: 'Inadequate seating in cafeteria',
    description: 'The cafeteria does not have enough seating. Many students have to eat standing up.',
    category: 'Cafeteria',
    status: 'Pending',
    studentId: 'STU025',
    studentName: 'Nour Hassan',
    submittedDate: '2026-03-27',
    agreementCount: 20,
    agreedBy: [],
  },
  {
    id: 'ALL24',
    title: 'Outdated computer systems',
    description: 'The computers in the computer labs are outdated and run slowly. Some are not functional.',
    category: 'Technology',
    status: 'In Progress',
    studentId: 'STU026',
    studentName: 'Amir Hassan',
    submittedDate: '2026-03-26',
    agreementCount: 11,
    agreedBy: [],
  },
  {
    id: 'ALL25',
    title: 'Insufficient hot water supply',
    description: 'Hot water is unavailable in dormitory bathrooms at certain times of the day.',
    category: 'Infrastructure',
    status: 'Pending',
    studentId: 'STU027',
    studentName: 'Zara Hassan',
    submittedDate: '2026-03-24',
    agreementCount: 8,
    agreedBy: [],
  },
  {
    id: 'ALL26',
    title: 'Poor signage on campus',
    description: 'Campus signage is unclear. New students have difficulty finding buildings and offices.',
    category: 'Others',
    status: 'Pending',
    studentId: 'STU028',
    studentName: 'Ibrahim Hassan',
    submittedDate: '2026-03-23',
    agreementCount: 5,
    agreedBy: [],
  },
  {
    id: 'ALL27',
    title: 'Food allergy concerns in cafeteria',
    description: 'The cafeteria does not clearly label foods containing allergens. This is a health risk.',
    category: 'Cafeteria',
    status: 'In Progress',
    studentId: 'STU029',
    studentName: 'Samar Hassan',
    submittedDate: '2026-03-21',
    agreementCount: 13,
    agreedBy: [],
  },
  {
    id: 'ALL28',
    title: 'Broken desk lamps in library',
    description: 'Many desk lamps in the library are broken. Study areas are poorly lit.',
    category: 'Infrastructure',
    status: 'Resolved',
    studentId: 'STU030',
    studentName: 'Hamza Hassan',
    submittedDate: '2026-03-19',
    agreementCount: 4,
    agreedBy: [],
  },
  {
    id: 'ALL29',
    title: 'Limited vegan food options',
    description: 'The cafeteria lacks sufficient vegan and vegetarian meal options for students.',
    category: 'Cafeteria',
    status: 'Pending',
    studentId: 'STU031',
    studentName: 'Yasmin Hassan',
    submittedDate: '2026-03-17',
    agreementCount: 9,
    agreedBy: [],
  },
  {
    id: 'ALL30',
    title: 'Security concerns at night',
    description: 'Campus security is insufficient at night. Students feel unsafe walking alone.',
    category: 'Safety',
    status: 'In Progress',
    studentId: 'STU032',
    studentName: 'Omar Hassan',
    submittedDate: '2026-03-16',
    agreementCount: 25,
    agreedBy: [],
  },
];

export const mockNotifications: Notification[] = [
  {
    id: 'N1',
    type: 'status_update',
    issueId: '1',
    issueTitle: 'Wifi not working in cafeteria',
    message: 'is now in progress',
    timestamp: '2026-04-25',
    read: false,
  },
  {
    id: 'N2',
    type: 'issue_resolved',
    issueId: '4',
    issueTitle: 'Broken projector in lab 2',
    message: 'has been resolved',
    timestamp: '2026-04-24',
    read: false,
  },
  {
    id: 'N3',
    type: 'staff_reply',
    issueId: 'MY2',
    issueTitle: 'Air conditioning not working in library',
    message: 'We\'ve received your request. A technician will visit the library tomorrow to diagnose the issue.',
    timestamp: '2026-04-23',
    read: false,
    staffName: 'Alem Alem',
  },
  {
    id: 'N4',
    type: 'status_update',
    issueId: 'MY7',
    issueTitle: 'Bathroom doors broken in block E',
    message: 'is now in progress',
    timestamp: '2026-04-22',
    read: false,
  },
  {
    id: 'N5',
    type: 'staff_reply',
    issueId: 'MY12',
    issueTitle: 'Internet connectivity issues in rooms',
    message: 'We are upgrading the WiFi infrastructure. Should be completed within 2 weeks.',
    timestamp: '2026-04-21',
    read: true,
    staffName: 'Sarah Ahmed',
  },
  {
    id: 'N6',
    type: 'issue_resolved',
    issueId: 'MY14',
    issueTitle: 'Broken window in classroom 102',
    message: 'has been resolved',
    timestamp: '2026-04-20',
    read: true,
  },
  {
    id: 'N7',
    type: 'status_update',
    issueId: 'MY17',
    issueTitle: 'Insufficient parking space',
    message: 'is now in progress',
    timestamp: '2026-04-19',
    read: true,
  },
  {
    id: 'N8',
    type: 'staff_reply',
    issueId: 'MY19',
    issueTitle: 'Drinking water contamination concern',
    message: 'Water quality tests have been completed. Results show water is safe. Testing is done monthly now.',
    timestamp: '2026-04-18',
    read: false,
    staffName: 'Karim Hassan',
  },
  {
    id: 'N9',
    type: 'status_update',
    issueId: 'MY11',
    issueTitle: 'Ventilation issues in dormitory',
    message: 'is now pending review',
    timestamp: '2026-04-17',
    read: false,
  },
  {
    id: 'N10',
    type: 'issue_resolved',
    issueId: 'MY20',
    issueTitle: 'Inadequate lighting in parking area',
    message: 'has been resolved',
    timestamp: '2026-04-16',
    read: false,
  },
];

// Mock staff members with assigned categories
export const mockStaff = [
  {
    id: 'STAFF001',
    name: 'Samuel Mekonnen',
    userId: 'STAFF001',
    role: 'staff' as const,
    registeredDate: '2026-01-15',
    staffCategory: 'Technology' as const,
  },
  {
    id: 'STAFF002',
    name: 'Alemu Fikre',
    userId: 'STAFF002',
    role: 'staff' as const,
    registeredDate: '2026-01-20',
    staffCategory: 'Cafeteria' as const,
  },
  {
    id: 'STAFF003',
    name: 'Fatuma Ahmed',
    userId: 'STAFF003',
    role: 'staff' as const,
    registeredDate: '2026-01-18',
    staffCategory: 'Infrastructure' as const,
  },
  {
    id: 'STAFF004',
    name: 'Dawit Abebe',
    userId: 'STAFF004',
    role: 'staff' as const,
    registeredDate: '2026-02-01',
    staffCategory: 'Cleanliness' as const,
  },
  {
    id: 'STAFF005',
    name: 'Zainab Hassan',
    userId: 'STAFF005',
    role: 'staff' as const,
    registeredDate: '2026-02-05',
    staffCategory: 'Safety' as const,
  },
];
